ceph/ceph-medic

ceph_medic/check.py
ceph_medic/connection.py
ceph_medic/remote/__init__.py
ceph_medic/remote/commands.py
ceph_medic/remote/util.py
ceph_medic/tests/checks/test_mons.py
ceph_medic/util/configuration.py

This also removes some unused code and introduces ``util.configuration._TrimIndentFile`` which helps us read ceph conf files into ``ConfigParser``.

Fixes unit test and flake8 failures

---

ceph_medic/checks/__init__.py
ceph_medic/util/configuration.py
tox.ini

Signed-off-by: Alfredo Deza <adeza@redhat.com>

tox: bump to python 3.5

---

ceph_medic/main.py

remove mention of cephdoctor in --help text

---

ceph_medic/collector.py

collector: skip node types that are not known to medic

---

ceph-medic.spec.in

Drop some old things that are no longer needed and align with Fedora's packaging guidelines.

rpm cleanups

---

ceph-medic.spec.in
setup.py

rpm: run unit tests during %check

---

docs/source/index.rst

... and it's a newer version (0.4.0) as well.

doc: tambo is in epel-testing

---

ceph_medic/check.py

We require an inventory now and do not do any autodiscovery with
the --monitor flag.

remove --monitor support from ceph_medic.check

---

docs/source/codes.rst
docs/source/codes/common.rst
docs/source/codes/mons.rst
docs/source/contents.rst

adds documentation for the exising error codes

---

docs/source/index.rst

docs: add install steps for repos from download.ceph.com

---

ceph_medic/runner.py
ceph_medic/tests/__init__.py
ceph_medic/tests/test_runner.py

fix total hosts count in runner

---

ceph_medic/runner.py
ceph_medic/terminal.py
ceph_medic/tests/test_terminal.py

Clear end of line

---

ceph_medic/runner.py
ceph_medic/tests/test_runner.py

We had the code in place but it wasn't writing anything to the terminal.
Fixes issue #26

give warnings on errors

---

ceph_medic/main.py

Give a new user a clue that "inventory" and "hosts file" are the same thing.

main: "inventory hosts file" in help text

---

docs/source/index.rst

Signed-off-by: iliul <liul124@chinaunicom.cn>

correct ceph-medic official download link

---

tests/functional/tox.ini

tests: adds ansible2.3 as a test environment

---

ceph_medic/checks/common.py
ceph_medic/tests/checks/test_common.py
ceph_medic/tests/conftest.py
docs/source/codes/common.rst

We were already collecting the version, we just consume it and raise an error otherwise
Fixes issue #69

Check installed version parity

---

ceph_medic/checks/osds.py
ceph_medic/tests/checks/test_osds.py
ceph_medic/tests/util/test_configuration.py
ceph_medic/util/configuration.py
docs/source/codes/osds.rst

warn on 'osd_pool_default_min_size=1' 

---

ceph_medic/checks/osds.py
ceph_medic/tests/checks/test_common.py
ceph_medic/tests/checks/test_osds.py
ceph_medic/tests/conftest.py
ceph_medic/tests/test_collector.py
ceph_medic/tests/test_log.py
ceph_medic/tests/test_runner.py

check for minimum amount of OSD nodes needed

---

ceph_medic/checks/mons.py
ceph_medic/tests/checks/test_mons.py
docs/source/codes/mons.rst

Fixes:
* https://github.com/ceph/ceph-medic/issues/72
* https://github.com/ceph/ceph-medic/issues/3

check number of monitor nodes

---

ceph_medic/checks/mons.py
ceph_medic/tests/checks/test_mons.py
docs/source/codes/mons.rst

warn on single monitor setups

---

ceph_medic/remote/functions.py
ceph_medic/tests/remote/test_functions.py

Fixes https://github.com/ceph/ceph-medic/issues/91

ensure no callables are included when calling stat remotely with Python 3

---

ceph_medic/__init__.py
ceph_medic/check.py
ceph_medic/collector.py
ceph_medic/compat.py
ceph_medic/connection.py
ceph_medic/main.py
ceph_medic/runner.py
ceph_medic/terminal.py
ceph_medic/tests/__init__.py
ceph_medic/tests/conftest.py
ceph_medic/tests/test_runner.py
ceph_medic/tests/util/test_hosts.py
ceph_medic/util/configuration.py
ceph_medic/util/hosts.py
docs/source/facts.rst
docs/source/index.rst
setup.py

This PR outgrew the initial intent of just adding docs and tests:
* Fixes https://github.com/ceph/ceph-medic/issues/90
* Adds a compat shim for Python3 imports
* Fixes a lot of Deprecation Warnings on Python 3
* Changes how configuration is set and accessed (via attributes instead of dict)
* Improves the padding for long hosts when reporting results
* Add/improve the documentation for container platform support
$ ceph-medic check
Host: rook-ceph-mgr-a-65445fd5f9-67bqm          connection: [failed     ]          
Host: rook-ceph-osd-0-84dfcbbf7-gtj79           connection: [failed     ]          
Host: rook-ceph-mon-a-7f94995d9c-qwwsb          connection: [connected  ]          
Host: rook-ceph-mon-b-958cf7785-2cstl           connection: [connected  ]               
Host: …

container platform cleanup and fixes

---

ceph_medic/checks/__init__.py
ceph_medic/checks/cluster.py
ceph_medic/runner.py
ceph_medic/tests/checks/test_cluster.py
docs/source/codes.rst
docs/source/codes/cluster.rst

Fixes issue #94 and partially fixes issue #84 !

error when there are no OSDs

---

ceph_medic/checks/common.py
ceph_medic/collector.py
ceph_medic/remote/commands.py
ceph_medic/tests/checks/test_common.py

Fixes https://github.com/ceph/ceph-medic/issues/79

checks: rgw_num_rados_handles should be 1

---

ceph_medic/connection.py

connection: do not use 'whoami' to test the connection, just call true

---

ceph_medic/tests/util/test_hosts.py
ceph_medic/util/hosts.py

Log the exception to the file, return a meaningful message to the terminal and set a non-zero exit status.
Fixes issue #99

better handle invalid JSON

---

ceph_medic/checks/common.py
ceph_medic/tests/checks/test_common.py
docs/source/codes/common.rst

Fixes: https://github.com/ceph/ceph-medic/issues/88

adds a check for a missing fsid in the ceph configuration

---

ceph_medic/checks/common.py
ceph_medic/checks/osds.py
ceph_medic/collector.py
ceph_medic/remote/commands.py
ceph_medic/runner.py
ceph_medic/tests/checks/test_cluster.py
ceph_medic/tests/checks/test_common.py
ceph_medic/tests/test_collector.py
ceph_medic/tests/test_runner.py
ceph_medic/util/__init__.py

Fixes wording on internal error reporting as well.
Fixes issue #106 #108

check admin socket for cluster FSIDs

---

README.rst
docs/source/index.rst

Modified installation.rst and README.rst to explain Kubernetes and OpenShift connection

Corrected explanation of container platform connection

---

ceph_medic/remote/commands.py
ceph_medic/tests/conftest.py
ceph_medic/tests/remote/test_commands.py
ceph_medic/tests/test_log.py

Adds tests and documents some fiixtures.
Fixes: https://github.com/ceph/ceph-medic/issues/132

Prevent non-zero exit status to break collection

---

ceph_medic/__init__.py
ceph_medic/checks/cluster.py
ceph_medic/collector.py
ceph_medic/remote/commands.py
ceph_medic/tests/checks/test_cluster.py
ceph_medic/tests/test_collector.py
docs/source/codes/cluster.rst
docs/source/index.rst

- Added check for cluster osd `nearfull: True`
- Wrote documentation and tests for nearfull check
- Merge with gabriellasroman/ceph-medic

Added check for cluster osd nearfull - issue #5 resolution

---

ceph_medic/checks/common.py
ceph_medic/checks/osds.py
ceph_medic/collector.py
ceph_medic/remote/commands.py
ceph_medic/tests/checks/test_osds.py
ceph_medic/tests/test_collector.py
docs/source/codes/osds.rst

checks: warn on unreasonable OSD ratios 

---

ceph_medic/main.py

replaced newly added indentations with 'spaces' in an attempt to correct the error in PR #144's build failure

testing 'tab' vs 'space' indentation

---

ceph_medic/__init__.py
ceph_medic/check.py
ceph_medic/collector.py
ceph_medic/connection.py
ceph_medic/main.py
ceph_medic/remote/commands.py
ceph_medic/tests/test_collector.py
ceph_medic/tests/util/test_hosts.py
ceph_medic/util/hosts.py
docs/source/changelog.rst
docs/source/index.rst

I've tested this on a podman cluster and on a bare-metal cluster. This adds a couple tests, and (I believe) documents the feature well enough.

Support for docker/podman deployments

---

ceph_medic/__init__.py
debian/changelog
docs/source/changelog.rst

Signed-off-by: Zack Cerza <zack@redhat.com>

Prepare for 1.0.6

---

ceph_medic/tests/test_main.py

Another (named)tuple tweak.
Signed-off-by: Zack Cerza <zack@redhat.com>

tests: One more py2/3 fix
