ceph_medic/collector.py, ceph_medic/tests/test_collector.py, tox.ini
Creates the util function ``ceph_medic.collector.get_path_metadata`` and tests it.  This also includes tests for ``ceph_medic.collector.collect_paths``.
=> tests and some refactoring in ceph_medic.collector

ceph_medic/collector.py, ceph_medic/tests/test_collector.py
When we set dirs[path] we need to stat 'path' and not 'i'.
This bug is exposed when no files or dirs are collected from the node.
=> fix bug in collector.get_path_metadata

setup.py
We import from execnet, so let's be explicit about requiring it
=> setup.py: require execnet

setup.py
We use setuptools to package ceph-medic, but we don't import from setuptools specifically within ceph-medic itself.
=> setup.py: do not require setuptools

MANIFEST.in
It's `bin/ceph-medic`, not `scripts/ceph-medic`, and setuptools already includes the `bin/` version because we pass it into `setup()` in `setup.py`.
=> MANIFEST.in: delete unused file

ceph_medic/tests/util/test_configuration.py, ceph_medic/util/configuration.py
We shouldn't store nodes in metadata['nodes'] that are not a part
of the ceph cluster, meaning they do not belong in a group that
ceph-medic knows as a ceph daemon type.
=> ignore host groups that do not exist in ceph_medic.metadata

setup.py
These are commands that automate some of the upstream release process.
The bump command will update the __version__ in ceph_medic/__init__.py
and the release command will create a new tag, push it to github and
release to pypi.
=> adds setup.py bump and setup.py release commands

tests/functional/.gitignore, tests/functional/Vagrantfile, tests/functional/centos7/Vagrantfile, tests/functional/centos7/group_vars/all, tests/functional/centos7/hosts, tests/functional/centos7/test.yml, tests/functional/centos7/vagrant_variables.yml, tests/functional/playbooks/setup.yml, tests/functional/scripts/generate_ssh_config.sh, tests/functional/tox.ini
This test will create 3 vagrant vms. A shaman repo for ceph-medic will
be installed on the client0 node. The rest of the nodes will be used
by ceph-ansible to create a ceph cluster. That cluster is then tested by
ceph-medic from the client0 node.
The goal is to run this test nightly with jenkins.
=> adds a functional test for centos7 shaman repos

tests/functional/Vagrantfile
This avoids errors like the following:
Call to virDomainCreateWithFlags failed: internal error: process exited
while connecting to monitor: 2017-07-10T23:27:52.339856Z
qemu-system-x86_64: CPU feature cmt not found
=> tests: set cpu_mode to host-paththrough for libvirt

docs/source/index.rst
The EPEL updates-testing period is over and I've pushed python-tambo to the stable repo. Drop the references to epel-testing.
=> doc: python-tambo is in the stable EPEL repo

ceph_medic/checks/osds.py, ceph_medic/tests/checks/test_osds.py, docs/source/codes.rst, docs/source/codes/osds.rst
This will issue the warning code WOSD1 if multiple
values are found in ceph_fsid files that are located
in the osd directories at /var/lib/ceph/osd
This is only a warning because you could want to host
OSDs on a single node for multiple ceph clusters.
Fixes: https://github.com/ceph/ceph-medic/issues/2
=> checks: adds osds.check_osd_ceph_fsid

debian/rules
Prior to this change, we were running pytest on the root-level "tests" directory, which was failing because it does not contain the unit tests.
=> debian: point pybuild at pytest directory

debian/ceph-doctor.install
The pybuild helper installs `/usr/bin/ceph-doctor` without this, since it just invokes setuptools to do the install, and we've configured `scripts/ceph-medic` in `setup.py`.
=> debian: delete old ceph-doctor file

ceph_medic/checks/mons.py, ceph_medic/runner.py, ceph_medic/tests/checks/test_mons.py, docs/source/codes/mons.rst
Fixes issue #30 
And fixes another issue with the runner where multi-errors where messed up:
------------ mons ------------
mira049
mira060                                                               eph-12,ceph-18
mira021                                                               ceph-22,ceph-23,ceph-10,ceph-66,ceph-74
EMON2: colocated OSDs found: ceph-5,ceph-6,ceph-11,ceph-15,ceph-17,ceph-19,ceph-20
To:
------------ mons ------------
mira049
EMON2: colocated OSDs found: ceph-7,ceph-46,ceph-40,ceph-49,ceph-8,ceph-12,ceph-18
mira060
EMON2: colocated OSDs found: ceph-1,ceph-69,ceph-25,ceph-26,ceph-27,ceph-22,ceph-23,ceph-10,ceph-66,ceph-74
mira021
EMON2: colocated OSDs found: ceph-5,ceph-6,ceph-11,ceph-15,ceph-17,ceph-19,ceph-20
=> colocated osds is a warning

ceph-medic.spec.in, ceph_medic/tests/test_main.py, debian/control
Test that we can simply import main.py.
This is really trivial, but at least we ensure that importing our dependencies (for example, tambo) works.
=> tests: add basic main test

ceph_medic/tests/util/test_configuration.py, ceph_medic/util/configuration.py
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1489444
=> show a nice error message if --inventory path doesn't exist

ceph_medic/main.py, ceph_medic/tests/test_main.py
If the path given to --ssh-config does not exist then ceph-medic stops
before checks are started and prints a message.
=> print friendly message with an invalid --ssh-config

tests/functional/centos7/group_vars/all
Our config for the test cluster needs updated to match the latest
changes to osd scenarios and install config options in ceph-ansible.
=> tests: update config to match latest ceph-ansible

ceph_medic/runner.py, ceph_medic/tests/__init__.py, ceph_medic/tests/conftest.py, ceph_medic/tests/test_runner.py
This is the second try to fix this problem:
node9
ECOM1: /etc/ceph/ceph.conf does not exist
ECOM2: ceph executable was not found in common paths when running `which`   ECOM2: ceph executable was not found in common paths when running `which`   ECOM3: /var/lib/ceph could not be parsed: [Errno 2] No such file or directory: '/va mira049                                                               ch file or directory: '/var/lib/ceph'   EMON1: secret key "None" is different than host(s): mira049,mira060,mira021
WMON2: collocated OSDs found: ceph-40,ceph-46,ceph-49,ceph-7,ceph-8,ceph-12,ceph-18
mira060                                                               erent than host(s): node9,node3
WMON2: collocated OSDs found: ceph-1,ceph-69,ceph-25,ceph-26,ceph-27,ceph-22,ceph-23,ceph-10,ceph-66 …
=> Test report output, and ensure newlines are added

ceph_medic/checks/mons.py
This one commit fixes both these issues:
#64 
#63 
One is when checking the current host, the other one is when comparing to a host that may not have the file. It is fine to skip/ignore because that should get picked up later by another check
=> checks: mons should not check against non-existing keys

debian/control
The test suite fails to run in pbuilder without these.
=> debian: Build-Depends test suite dependencies

ceph_medic/checks/common.py, ceph_medic/tests/checks/test_common.py, docs/source/codes/common.rst
Fixes: https://github.com/ceph/ceph-medic/issues/65
=> adds a check for parity between installed and socket versions

tests/functional/tox.ini
Fixes this issue when running tests:
fatal: [osd0]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ", "unreachable": true}
=> tests increase the ssh retries from 0 to 5

tests/functional/tox.ini
ceph-ansible now requires this library for config validation. This also adds an ``ansible2.4`` factor.
=> tests: install notario when running functional tests

ceph_medic/checks/osds.py, ceph_medic/tests/checks/test_osds.py
Although the min_size check is correct, the message displayed on screen is incorrect. 
Changing from "osd default pool size is set to 1" to "osd default pool min_size is set to 1"
=> Fix typo in osds.py when checking pool default min_size

ceph_medic/__init__.py, ceph_medic/collector.py, ceph_medic/connection.py, ceph_medic/decorators.py, ceph_medic/generate.py, ceph_medic/main.py, ceph_medic/remote/functions.py, ceph_medic/runner.py, ceph_medic/util/configuration.py, setup.py, tox.ini
This brings full support for openshift and kubernetes checks to ceph-medic. We are able to dynamically generate the hosts to connect to, and provide the same experience as baremetal-provisioned hosts.
There is quite a bit to update and clean up, but wanted to get this PR out, and follow up with docs and clean up (see `XXX` and `TODO`s)
=> kubernetes and openshift support

ceph_medic/check.py
=> check: set a non-zero exit status on errors, warnings, or failures

ceph_medic/check.py, ceph_medic/runner.py, ceph_medic/tests/test_runner.py
Fixes issue #101 by separating errors and warnings from the "failed" bucket. This removes `failed` as it will be possible in the future to not _fail_ on anything or fail on warnings for example. The wording will not be able to keep up with the configuration, so `failed` is removed, and we limit the reporting on warnings, errors, and internal errors.
=> Separate warnings and errors from failures

ceph_medic/checks/common.py, ceph_medic/collector.py, ceph_medic/tests/checks/test_common.py, ceph_medic/tests/conftest.py, docs/source/codes/common.rst
These are now caught in the `common` module, so that regardless of the host type (mon or osd) it will report the problem.
Finishes the fixes needed for #30 
Fixes: #110 which was causing breakage due to a monmap in /var/lib/ceph/tmp
=> Error on collocated mons with OSDs

ceph_medic/check.py, ceph_medic/remote/functions.py, ceph_medic/tests/remote/test_functions.py
Allows to ignore codes, either in the CLI or in the configuration. Using the CLI overrides anything described in the configuration.
It also addresses the problem of possible exceptions being raised when trying to capture remote errors, adds tests to verify this.
Fixes issues: 
https://github.com/ceph/ceph-medic/issues/116
https://github.com/ceph/ceph-medic/issues/111
=> codes: actually be able to ignore them

ceph_medic/compat.py
The compatibility layer can get messed up by the 'configparser' package
that is available in Python 2.7 which clashes with 3.6
By giving preference to importing from ConfigParser as it is in 2.7 we
prevent the problem of NoOptionError not showing up correctly.
Signed-off-by: Alfredo Deza <adeza@redhat.com>
=> compat: swap the order of configparser import

ceph_medic/__init__.py, ceph_medic/tests/test_main.py, debian/changelog, docs/source/changelog.rst
Aside from the dependency issues, it turns out I made two mistakes when updating tests when I added the docker support.
=> Fix test bugs that were breaking rpm builds
